package itech3209;
//Generated by Selenium IDE
import org.junit.Test;
import org.junit.internal.TextListener;
import org.junit.runner.JUnitCore;
import org.junit.runner.Result;
import org.junit.Before;
import org.junit.After;
import java.util.*;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebDriverException;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.StaleElementReferenceException;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import static org.junit.Assert.assertEquals;

/* this class tests the registration process, by checking the alert message it verifies if the registration is successful. 
 * This test asserts the user login name matches user name in the database and the validates that user can login successfully
 * by checking the logout button. 
 * 
 */

public class registration {
	private WebDriver driver;
	private Map<String, Object> vars;
	
	JavascriptExecutor js;
	XSSFWorkbook workbook;
	XSSFSheet sheet;
	XSSFCell cell; 

	public static void main(String args[]) {
		  JUnitCore junit = new JUnitCore();
		  junit.addListener(new TextListener(System.out));
		  Result result = junit.run(registration.class); // Replace "SampleTest" with the name of your class
		  if (result.getFailureCount() > 0) {
		    System.out.println("Test failed.");
		    System.exit(1);
		  } else {
		    System.out.println("Test finished successfully.");
		    System.exit(0);
		  }
	}
	
	@Before
	public void setUp() {
	 System.setProperty("webdriver.chrome.driver","D:/selenium/study3209/selenium driver/chromedriver.exe");
	 driver = new ChromeDriver();
	 js = (JavascriptExecutor) driver;
	 vars = new HashMap<String, Object>();
	}
	
	@After
	public void tearDown() {
	 driver.quit();
	}

	@Test
	public void testRegistration() throws InterruptedException, IOException {
		// load file
		/*In the default registration workbook we validate two scenarios:
		 * if data is valid then "Account Created" alert message should pops up 
		 * if username or email already exists then expected message should be "Username or Email exists" */
		
		File src=new File("data/registration.xlsx"); 
		
		FileInputStream finput = new FileInputStream(src); 
		
		// Load the workbook. 
	
		workbook = new XSSFWorkbook(finput); 
	
		// Load the sheet in which data is stored. 
	
		sheet= workbook.getSheetAt(0); 
		
		for(int i=1;  i<=sheet.getLastRowNum(); i++) { 			
		
			try	 
			
			{	
				//set userName
				cell = sheet.getRow(i).getCell(0); 
				cell.setCellType(CellType.STRING);  
				String userName = cell.getStringCellValue(); 
				System.out.println(userName);
			
				//set email
				cell = sheet.getRow(i).getCell(1); 
				cell.setCellType(CellType.STRING);  
				String email = cell.getStringCellValue(); 
				System.out.println(email);
				
				//set primary language	
				cell = sheet.getRow(i).getCell(2); 
				cell.setCellType(CellType.STRING);  
				String primaryLag = cell.getStringCellValue(); 
				System.out.println(primaryLag);
				
				//set password
				cell = sheet.getRow(i).getCell(3); 
				cell.setCellType(CellType.STRING);  
				String password = cell.getStringCellValue(); 
				System.out.println(password);
				
				// start registration process				
				driver.get("http://localhost/ITECH3208_LanguageClub/loginpage.php");			
			    driver.manage().window().setSize(new Dimension(1936, 1056));
			    driver.findElement(By.name("Register")).click();
			    Thread.sleep(5000);
			    driver.findElement(By.name("username")).click();
			    driver.findElement(By.name("username")).sendKeys(userName);
			    driver.findElement(By.name("email")).click();
			    driver.findElement(By.name("email")).sendKeys(email);
			    driver.findElement(By.name("primarylag")).click();
			    {
			      WebElement dropdown = driver.findElement(By.name("primarylag"));
			      dropdown.findElement(By.xpath("//option[. = '" + primaryLag + "']")).click();
			    }
			    driver.findElement(By.name("primarylag")).click();
			    driver.findElement(By.name("password_1")).click();
			    driver.findElement(By.name("password_1")).sendKeys(password);
			    driver.findElement(By.name("password_2")).click();
			    driver.findElement(By.name("password_2")).sendKeys(password);
			    driver.findElement(By.id("t&C")).click();
			    driver.findElement(By.name("reg_user")).click();
			    
			 		    
			    
			    // Switching to Alert        
//			    Alert alert = driver.switchTo().alert();		
//			   		
//			    // Capturing alert message.    
//			    String alertMessage= driver.switchTo().alert().getText();	
//			    
//					
//			    if (alertMessage !="") {
//			    // Displaying alert message		
//				    System.out.println(alertMessage );			   
//				    // Accepting alert		
//				    alert.accept();	
//				    
//			    } else { 
			    
			    driver.findElement(By.cssSelector(".login_form-title")).click();			    
			    driver.findElement(By.cssSelector(".whitebox")).click();
			    driver.findElement(By.id("username")).sendKeys(userName);
			    driver.findElement(By.id("password")).sendKeys(password);
			    driver.findElement(By.name("Login")).click();
			    
			    //assert the user login name matches user name in the database
			    String loginName = driver.findElement(By.cssSelector(".nav_sub_heading:nth-child(3)")).getText();
			    System.out.println(loginName);
			    assertEquals(loginName, userName);
			    
			    driver.findElement(By.linkText("Log out")).click();
			    System.out.println ("log out buttion found, user login successfully :" + loginName);
			    }		    
			    		
		
			catch (NoSuchElementException ne)
	        {     	
			     ne.printStackTrace();
	        }				
		    catch(StaleElementReferenceException se) 
	        {					
				 se.printStackTrace();
			}		
			catch (WebDriverException e) 
			{
				e.printStackTrace();
			}
			catch (Throwable t)
		    {
		       t.printStackTrace();
		    
		} 
		
	 }
	
	
	}
}
